/** Auto-generated by scripts/extract-logo-trace.mjs — do not edit manually. */
export const LOGO_TRACE_VIEWBOX = 128
export const LOGO_TRACE_PATH_LENGTH = 612
/** Closed-loop length (open + closing segment); debug / preview only. */
export const LOGO_TRACE_PATH_LENGTH_CLOSED = 613
/** Outer silhouette traced from src/assets/logo.png (alpha contour). */
export const LOGO_TRACE_OUTLINE =
  'M 119 5.3 L 123 5.3 L 124 6.8 L 124 101.3 L 123 102.8 L 103.5 122.8 L 100.5 122.8 L 100.5 99.3 L 99.5 98.8 L 76 122.8 L 73.5 122.8 L 73.5 68.8 L 73 68.3 L 66 74.3 L 64.5 74.8 L 55.5 67.3 L 55 67.8 L 55 122.8 L 20 122.8 L 4 105.3 L 4 10.8 L 4.5 9.8 L 5.5 8.8 L 10 7.3 L 13 7.3 L 65.5 36.8 L 104.5 13.3 L 118.5 5.8'

/**
 * LOCKED — brand startup splash timing (product design, do not change casually).
 *
 * - One full cycle = exactly 5 seconds wall-clock.
 * - The trail dot travels the M outer silhouette once per cycle (SMIL animateMotion + stroke-dash).
 * - 82% of the cycle = draw; remaining 18% = hold at end + subtle fade (not a second lap).
 * - App shell enters at STARTUP_FORCE_ENTER_MS (5.5s) — see startupUx.ts.
 *
 * All animation dur/keyTimes/CSS --startup-cycle MUST derive from these constants only.
 * CI guard: src/test/startupUx.test.ts
 */
export const STARTUP_SPLASH_CYCLE_S = 5
/** Fraction of cycle spent drawing the M outline (0–1); rest = hold + fade within the same 5s cycle. */
export const STARTUP_SPLASH_DRAW_RATIO = 0.82
