import { vi } from 'vitest'
import type { ElectronAPI } from '../types/electron'

const electronAPI: ElectronAPI = {
  readFile: vi.fn(),
  readFileBase64: vi.fn(async () => ({ success: true, data: '', mimeType: 'application/pdf' })),
  writeFile: vi.fn(),
  listFiles: vi.fn(),
  deleteFile: vi.fn(),
  selectDirectory: vi.fn(),
  selectFile: vi.fn(),
  saveFileDialog: vi.fn(),
  fileExists: vi.fn(),
  openExternal: vi.fn(),
  writeClipboardText: vi.fn(() => true),
  getAppVersion: vi.fn(async () => '0.1.0'),
  getDatabaseStatus: vi.fn(async () => ({ available: true })),
  waitDesktopReady: vi.fn(async () => ({ ready: true })),
  onDesktopReady: vi.fn(() => () => {}),
  createDirectory: vi.fn(),
  getFileStats: vi.fn(),
  renameFile: vi.fn(),
  watchDirectory: vi.fn(),
  unwatchDirectory: vi.fn(),
  onFileChanged: vi.fn(),
  onWatchError: vi.fn(),
  removeFileChangedListener: vi.fn(),
  removeWatchErrorListener: vi.fn(),
  openInExplorer: vi.fn(),
  syncWorkspacePath: vi.fn(async () => ({ success: true })),
  initWorkspace: vi.fn(),
  reinitWorkspace: vi.fn(),
  detectLegacyPaths: vi.fn(async () => ({ success: true, legacy: [], needsMigration: false })),
  migrateWorkspace: vi.fn(async () => ({ success: true, migrated: [], skipped: [] })),
  checkCliAvailable: vi.fn(),
  installCli: vi.fn(),
  uninstallCli: vi.fn(),
  readTextFile: vi.fn(),
  writeTextFile: vi.fn(),
  pathIsAbsolute: async (filePath: string) => filePath.startsWith('/') || filePath.match(/^[A-Z]:\\/i) !== null,
  pathJoin: async (...paths: string[]) => paths.join('/'),
  pathResolve: async (...paths: string[]) => paths.join('/'),
  pathRelative: async (from: string, to: string) => to.replace(from, ''),
  getSettings: vi.fn(),
  saveSettings: vi.fn(),
  windowMinimize: vi.fn(),
  windowMaximize: vi.fn(),
  windowClose: vi.fn(),
  windowIsMaximized: vi.fn(),
  path: {
    basename: vi.fn(async (filePath: string) => filePath.split(/[/\\]/).pop() || filePath),
    join: vi.fn(async (...paths: string[]) => paths.join('/')),
    dirname: vi.fn(async (filePath: string) => filePath.split(/[/\\]/).slice(0, -1).join('/') || '.'),
    resolve: vi.fn(async (...paths: string[]) => paths.join('/')),
    isAbsolute: vi.fn(async (filePath: string) => filePath.startsWith('/') || filePath.match(/^[A-Z]:\\/i) !== null),
    relative: vi.fn(async (from: string, to: string) => to.replace(from, '')),
  },
  terminal: {
    start: vi.fn(),
    input: vi.fn(),
    resize: vi.fn(),
    kill: vi.fn(),
    onOutput: vi.fn(),
    removeOutputListener: vi.fn(),
    removeListeners: vi.fn(),
  },
  window: {
    minimize: vi.fn(),
    maximize: vi.fn(),
    close: vi.fn(),
    isMaximized: vi.fn(),
    onMaximizeChange: vi.fn(),
  },
  vaultApi: {
    start: vi.fn(async () => ({ success: true, port: 17333 })),
    stop: vi.fn(async () => ({ success: true })),
    getStatus: vi.fn(async () => ({ running: false, port: 17333, workspacePath: '' })),
    getLanAddresses: vi.fn(async () => ({ addresses: ['192.168.1.100'] })),
  },
  ollama: {
    getStatus: vi.fn(async () => ({
      running: false,
      baseUrl: 'http://127.0.0.1:11434',
      models: [],
    })),
  },
  speech: {
    isAvailable: vi.fn(async () => ({ available: false })),
    start: vi.fn(async () => ({ success: false })),
    stop: vi.fn(async () => ({ success: true })),
    onTranscript: vi.fn(() => () => {}),
    onError: vi.fn(() => () => {}),
  },
  calendar: {
    pickFile: vi.fn(async () => ({ canceled: true })),
    getEvents: vi.fn(async () => ({
      success: true,
      events: [],
      source: null,
      date: '2025-06-19',
    })),
  },
  intelligence: {
    prepareImport: vi.fn(async () => ({ success: false, error: 'mock' })),
    prepareUrl: vi.fn(async () => ({ success: false, error: 'mock' })),
    isImportable: vi.fn(async () => ({ importable: false })),
  },
  acp: {
    detectAgents: vi.fn(),
    getAllInstalledAgents: vi.fn(),
    setCliAgentEnabled: vi.fn(),
    onCliAgentsChanged: vi.fn(() => () => {}),
    getBackends: vi.fn(),
    setWorkspacePath: vi.fn(),
    connect: vi.fn(),
    ensureSession: vi.fn(),
    checkAgentHealth: vi.fn(async () => ({ available: true })),
    newSession: vi.fn(),
    authenticate: vi.fn(),
    getAuthMethods: vi.fn(),
    openGeminiTerminalLogin: vi.fn(async () => ({ success: true })),
    checkGeminiAuth: vi.fn(async () => ({ authenticated: true })),
    reloadSessions: vi.fn(),
    refreshAgents: vi.fn(),
    syncWorkspaceSkills: vi.fn(),
    getMcpServersConfig: vi.fn(),
    sendPrompt: vi.fn(),
    cancelPrompt: vi.fn(),
    setMode: vi.fn(),
    setModel: vi.fn(),
    getMode: vi.fn(),
    getModels: vi.fn(),
    getSessionInfo: vi.fn(),
    clearSession: vi.fn(),
    disconnect: vi.fn(),
    getConversationHistory: vi.fn(async () => ({ messages: [], total: 0, hasMore: false })),
    clearConversationHistory: vi.fn(),
    switchBackend: vi.fn(),
    selectBackend: vi.fn(),
    getConnectionStatus: vi.fn(async () => ({ connected: false, hasSession: false, ready: false, needsAuth: false })),
    getAllConnectionStatuses: vi.fn(async () => ({})),
    invalidateCloudReachability: vi.fn(async () => ({ success: true })),
    warmupAllAgents: vi.fn(async () => ({ success: true, count: 0 })),
    onSessionUpdate: vi.fn(),
    onAcpStreamMessage: vi.fn(() => () => {}),
    onBackendReady: vi.fn(() => () => {}),
    onConnectionStatusChange: vi.fn(() => () => {}),
    onAgentStatus: vi.fn(() => () => {}),
    onPermissionRequest: vi.fn(),
    onAuthUrl: vi.fn(() => () => {}),
    onAuthDeprecated: vi.fn(() => () => {}),
    onDisconnected: vi.fn(() => () => {}),
    onEndTurn: vi.fn(),
    removeListeners: vi.fn(),
    respondToPermission: vi.fn(),
    rejectPermission: vi.fn(),
    getAvailableCommands: vi.fn(async () => []),
    autoTestMessage: vi.fn(),
    readSkillFile: vi.fn(),
  }
}

;(globalThis as any).window = { electronAPI }

vi.stubGlobal('window', { electronAPI })

const localStorageMock = {
  getItem: vi.fn(() => null),
  setItem: vi.fn(),
  removeItem: vi.fn(),
  clear: vi.fn(),
  key: vi.fn(() => null),
  length: 0,
}
vi.stubGlobal('localStorage', localStorageMock)
